name: バグ報告 (Bug)
description: 不具合を報告する
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 何が起きているか
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
    validations:
      required: false
